dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:3.5.6"
    }
}
dependencies {
    //redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    //s3
    implementation 'org.springframework.cloud:spring-cloud-starter-aws:2.2.6.RELEASE'
}

clean {
    delete file('src/main/generated')
}

jar { enabled = true }