dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:3.3.5"
    }
}
dependencies {
    implementation project(':core')
    implementation project(':common')

    //websocket
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
}

jar { enabled = true }